services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    container_name: api_container
    image: nodeapp
    ports:
      - 3030:3030
    depends_on: 
      - mongo_db
    environment:
      - MONGODB_URI=mongodb+srv://meadowmonbusiness:NXVwZOXBQChb01uj@cluster0.mongodb.net/MeadowMon?retryWrites=true&w=majority
      - REACT_APP_BACKEND_URL=http://localhost:8000
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo_db:27017/yourdbname

volumes:
  mongo_data: {}