apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: product
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      run: product
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: product
    spec:
      containers:
      - image: product:latest
        imagePullPolicy: Always
        name: product
        ports:
        - containerPort: 8000
          protocol: TCP
      restartPolicy: Always
