version: '3'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  api:
    container_name: api_container
    build: .
    ports:
      - 4000:3000
    depends_on: 
      - mongo_db
    environment:
      - MONGODB_URI=mongodb+srv://meadowmonbusiness:NXVwZOXBQChb01uj@meadowmon.zcf42.mongodb.net/MeadowMon?retryWrites=true&w=majority
      - NODE_ENV=development
    volumes:
      - ./data:/app/database/data

volumes:
  mongo_data: {}